### ISSUE TITLE
Marshal SOQL queries with OR operators between different columns

### ISSUE THREAD

**Issue by t-margheim** [forcedotcom/go-soql#13]
Marshal SOQL queries with `OR` operators between different columns.  For example, I don't believe this query is currently marshal-able: 

``` sql
SELECT Name,Email,Phone
FROM Contact
WHERE Title = 'Purchasing Manager' OR Department = 'Accounting'
```

I've been playing with an implementation that I think might work and is in keeping with the current patterns: adding an optional clause tag called `joiner` for `whereClause`.  If not set, the marshal function uses `AND` to join (to maintain current functionality).  If it's set to `OR` (case insensitive), then it will separate the clauses with `OR`.

``` go
type contact struct {
	Name  string `soql:"selectColumn,fieldName=Name" json:"Name"`
	Email string `soql:"selectColumn,fieldName=Email" json:"Email"`
	Phone string `soql:"selectColumn,fieldName=Phone" json:"Phone"`
}

type orSOQLQuery struct {
	SelectClause contact                `soql:"selectClause,tableName=Contact"`
	WhereClause  positionOrDeptCriteria `soql:"whereClause,joiner=OR"`
}

type positionOrDeptCriteria struct {
	Title      string `soql:"equalsOperator,fieldName=Title"`
	Department string `soql:"equalsOperator,fieldName=Department"`
}

// this would generate the soql query
soql.Marshal(orSOQLQuery{
    WhereClause: positionOrDeptCriteria{
        Title:      "Purchasing Manager",
        Department: "Accounting",
    },
})
```

**Comment by atulkc** [comment]
Thanks @t-margheim for submitting the issue and corresponding [PR](https://github.com/forcedotcom/go-soql/pull/15). I think this is a great addition to this library.
