### ISSUE TITLE
Escape %_ in LIKE expression

### ISSUE THREAD

**Issue by tuchida** [forcedotcom/go-soql#26]
```go
type WhereClause struct {
	IncludeNamePattern []string `soql:"likeOperator,fieldName=Name"`
}

// ...

soqlStruct.WhereClause.IncludeNamePattern = []string{"%_"}
s, err := soql.Marshal(soqlStruct)
```
actual: `WHERE Name LIKE '%%_%'`
expected: `WHERE Name LIKE '%\%\_%'`

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_quotedstringescapes.htm

If there is no problem, I will create Pull Request.

**Comment by tuchida** [comment]
`\` => `\\`
If you don't convert this too, they can destroy the close single quote.

**Comment by atulkc** [comment]
@tuchida good catch! If you can submit PR for this I will really appreciate it. Thanks!

**Comment by tuchida** [comment]
Thanks!
