### ISSUE TITLE
*bool is not supported in buildEqualsClause

### ISSUE THREAD

**Issue by dmaykov** [forcedotcom/go-soql#9]
There is an issue with boolean conditions in buildEqualsClause: when bool fields are initialized, they default to "false" if a condition is not present, which Is not necessarily desirable behavior. I suggest to add *bool support and ignore those field if they're nil.

**Comment by atulkc** [comment]
Thanks for filing the issue. I will schedule this to be done in next couple of weeks. Sorry for the delay in response!

**Comment by atulkc** [comment]
Closed by https://github.com/forcedotcom/go-soql/pull/12
